name: mix
description: An expressive way to effortlessly build design systems in Flutter.
version: 1.2.0
homepage: https://github.com/leoafarias/mix

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=3.10.6"
  
dependencies:
  mix_annotations: ^0.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  dart_code_metrics_presets: ^2.13.0
  build_runner: ^2.4.9
  mix_generator: ^0.2.0

# flutter:
  # assets:

